version: '3.6'
services:
  databse:
    image: shamera82/db
    container_name: dbserver
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports: 
      - "3306:3306"
    networks:
      stack:
        ipv4_address: 172.20.1.2
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql


  appserver:
    image: shamera82/app
    container_name: appserver
    environment:
      - MYSQL_HOST=dbserver
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3000:3000"
    networks:
      stack:
        ipv4_address: 172.20.1.3
    restart: always

  webserver:
    image: shamera82/web 
    container_name: webserver
    environment:
      - APP_SVR_NAME=appserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
    #  - './webserver/nginx.conf:/etc/nginx/nginx.conf:ro'
      - web_log:/var/log/nginx
    networks:
      stack:
        ipv4_address: 172.20.1.4
    restart: always


networks: 
  stack:
    ipam:
      config:
        - subnet: 172.20.1.0/24

volumes:
  mysql_data:
  web_log:
